In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import keras
import tensorflow

Using TensorFlow backend.
/home/anubhav/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/anubhav/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/anubhav/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/anubhav/.local/lib/python3.7/site-packages/tensorflow/py

In [3]:
import os
files=os.listdir('/home/anubhav/Downloads/44109_78156_bundle_archive/UTKFace')

In [4]:
files[0]

'51_0_1_20170117173705235.jpg.chip.jpg'

In [5]:
len(files)

23708

In [6]:
files[0].split('_')[0]

'51'

In [7]:
age_classes=[]
for i in range(0,len(files)):
    age=files[i].split('_')[0]
    print(age)
    age = int(age)
    if age <= 14:
        age_classes.append(0)
    if (age>14) and (age<=25):
        age_classes.append(1)
    if (age>25) and (age<40):
        age_classes.append(2)
    if (age>=40) and (age<60):
        age_classes.append(3)
    if age>=60:
        age_classes.append(4)
    

51
36
40
70
58
34
26
85
25
17
60
35
49
1
1
26
26
2
50
32
60
20
67
65
30
27
62
58
23
34
3
39
24
1
26
52
50
28
36
25
55
25
26
28
40
23
26
40
1
1
34
27
25
26
42
29
18
26
24
66
60
56
82
18
33
20
23
26
49
24
26
74
28
35
60
45
13
24
20
23
50
1
18
29
46
45
21
35
26
26
32
38
26
24
1
33
85
26
30
21
35
30
49
75
33
49
24
43
23
26
37
70
25
72
2
52
53
52
54
25
6
34
16
42
60
68
35
74
35
50
36
1
42
8
50
24
55
4
37
68
29
32
26
35
39
34
34
30
48
12
65
27
73
51
26
1
12
4
20
6
26
39
36
25
31
26
41
1
45
54
45
35
22
61
23
28
26
24
35
1
37
21
23
1
26
63
29
32
45
26
1
75
50
25
28
29
30
40
21
32
35
24
25
26
26
1
74
26
58
26
54
38
70
3
35
88
45
26
17
32
31
111
10
25
16
26
1
35
8
27
30
24
32
40
60
32
39
24
14
10
9
40
11
4
16
23
26
2
26
76
24
37
42
40
16
25
92
3
35
75
26
26
69
34
26
26
65
34
65
32
16
28
61
1
36
26
27
35
22
46
57
34
9
24
55
29
66
32
45
26
32
26
26
8
3
53
42
50
8
21
22
45
26
47
22
29
50
34
80
33
7
49
24
1
15
24
43
28
23
35
21
64
25
28
9
28
35
10
24
8
9
51
24
32
39
34
42
30
26
38
30
46
43
66
48
34


In [8]:
from PIL.Image import *

In [9]:
faces=[]
for i in range(0,len(files)):
   
    image=open('/home/anubhav/Downloads/44109_78156_bundle_archive/UTKFace/'+files[i])
    image=image.resize((32,32))
    image=np.asarray(image)
    faces.append(image)
    print('done')

done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done


In [10]:
faces=np.squeeze(faces)

In [11]:
faces.shape

(23708, 32, 32, 3)

In [12]:
faces=faces.astype('float32')
faces=faces/255

In [13]:
from keras.models import Sequential
from keras.layers import *

In [80]:
model=Sequential()
model.add(Conv2D(64,kernel_size=(3,3),activation='relu',input_shape=(32,32,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32,kernel_size=(2,2),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.20))
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.15))
model.add(Dense(5,activation='softmax'))

In [81]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 30, 30, 64)        1792      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 15, 15, 64)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 14, 14, 32)        8224      
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 7, 7, 32)          0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 7, 7, 32)          0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 1568)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 256)              

In [82]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [17]:
from keras.utils.np_utils import to_categorical

In [18]:
age_classes=to_categorical(age_classes,num_classes=5)

In [21]:
faces

array([[[[0.6392157 , 0.5764706 , 0.47843137],
         [0.7882353 , 0.7254902 , 0.62352943],
         [0.84313726, 0.78431374, 0.6627451 ],
         ...,
         [0.5019608 , 0.48235294, 0.47058824],
         [0.4745098 , 0.45490196, 0.44313726],
         [0.5254902 , 0.49019608, 0.45490196]],

        [[0.61960787, 0.5686275 , 0.5058824 ],
         [0.6862745 , 0.63529414, 0.56078434],
         [0.7254902 , 0.6784314 , 0.5921569 ],
         ...,
         [0.31764707, 0.28627452, 0.2784314 ],
         [0.22352941, 0.19215687, 0.18431373],
         [0.15294118, 0.1254902 , 0.09411765]],

        [[0.12941177, 0.10196079, 0.07843138],
         [0.14509805, 0.11764706, 0.08627451],
         [0.15686275, 0.12941177, 0.09019608],
         ...,
         [0.12941177, 0.08235294, 0.08235294],
         [0.12941177, 0.08235294, 0.08235294],
         [0.1254902 , 0.11372549, 0.09411765]],

        ...,

        [[0.8666667 , 0.77254903, 0.6392157 ],
         [0.8980392 , 0.8039216 , 0.67058825]

In [83]:
model.fit(faces,age_classes,epochs=25)

Epoch 1/25
23708/23708 [==============================] - 25s 1ms/step - loss: 1.1326 - accuracy: 0.5162
Epoch 2/25
23708/23708 [==============================] - 24s 994us/step - loss: 0.9658 - accuracy: 0.5874
Epoch 3/25
23708/23708 [==============================] - 24s 997us/step - loss: 0.9122 - accuracy: 0.6084
Epoch 4/25
23708/23708 [==============================] - 24s 1ms/step - loss: 0.8729 - accuracy: 0.6183
Epoch 5/25
23708/23708 [==============================] - 24s 1ms/step - loss: 0.8472 - accuracy: 0.6315
Epoch 6/25
23708/23708 [==============================] - 25s 1ms/step - loss: 0.8170 - accuracy: 0.6452
Epoch 7/25
23708/23708 [==============================] - 24s 1ms/step - loss: 0.7946 - accuracy: 0.6533
Epoch 8/25
23708/23708 [==============================] - 24s 1ms/step - loss: 0.7633 - accuracy: 0.6657
Epoch 9/25
23708/23708 [==============================] - 24s 1ms/step - loss: 0.7395 - accuracy: 0.6802
Epoch 10/25
23708/23708 [==========================

In [84]:
model.save('age_kaggle_b.h5')

In [85]:
image_dt=open('/home/anubhav/Desktop/emma.jpg')

In [86]:
image_dt=image_dt.resize((32,32))

In [87]:
image_dt=np.expand_dims(image_dt,axis=0)

In [88]:
image_dt=image_dt/255

In [89]:
image_dt

array([[[[0.8       , 0.84705882, 0.76078431],
         [0.86666667, 0.98431373, 0.98431373],
         [0.83921569, 0.93333333, 0.94117647],
         ...,
         [0.30588235, 0.34901961, 0.37254902],
         [0.31764706, 0.35686275, 0.39215686],
         [0.18039216, 0.2       , 0.22352941]],

        [[0.86666667, 0.91764706, 0.84705882],
         [0.91372549, 1.        , 0.99215686],
         [0.91764706, 1.        , 0.99607843],
         ...,
         [0.25882353, 0.27058824, 0.29019608],
         [0.14901961, 0.18823529, 0.19607843],
         [0.14901961, 0.19607843, 0.24313725]],

        [[0.83529412, 0.88235294, 0.78823529],
         [0.8745098 , 0.99607843, 0.97254902],
         [0.89019608, 1.        , 0.99607843],
         ...,
         [0.15686275, 0.16862745, 0.18823529],
         [0.15294118, 0.15686275, 0.17647059],
         [0.14117647, 0.16078431, 0.17647059]],

        ...,

        [[0.        , 0.00392157, 0.02352941],
         [1.        , 1.        , 0.98431373]

In [90]:
result=model.predict_classes(image_dt)

In [91]:
result

array([4])